<?php

namespace TunisiaMall\TMBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OkRepository extends EntityRepository
{
    public function myFindIn($array)
{
  $query = $this->_em->createQuery('SELECT a FROM OCPlatformBundle:Advert a');

  $qb
    ->where('a.id = :id')
    ->setParameter('id', $id)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
}
}
