imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    http_method_override: true
    translator: ~
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TunisiaMall\UserBundle\Entity\User
    
services:
    fos_user.doctrine_registry:
        alias: doctrine
    twig.extension.intl: 
        class: Twig_Extensions_Extension_Intl 
        tags: 
                - { name: twig.extension }  
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
        
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    http_client:
        verify_peer: false
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           248369388839956
            client_secret:       fc0160dfaa245ea78fba34b6bbd5b0b3
            scope:         "email, basic_info, user_birthday"
            infos_url:     "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,birthday,picture.type(square)"
            paths:
                profilepicture: picture.data.url
        google:
            type:                google
            client_id:           744233870884-tj7s989ccrmk9odd6mt1rnkvkhv03ua8.apps.googleusercontent.com
            client_secret:       IB7utBnNksRGKCmLbYjHywtr
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
#        twitter:
#            type:                twitter
#            client_id:           yVG2lheWELadfOepWxKza8MBF
#            client_secret:       9pohtP6yJyZV2kTaMDUZoiTH3V8Snq5H4V0sCu014HDm7utgqY
#            scope:               "" 
        windows_live:
            type:                windows_live
            client_id:           000000004018F43D
            client_secret:       CTrVHT7RDPFkKbiQHQVebG1WMoIKclb-
            scope:               "wl.emails wl.basic wl.signin wl.birthday wl.phone_numbers wl.postal_addresses"
#        github:
#            type:                github
#            client_id:           faec7bec9d91fd4c60fc
#            client_secret:       ca68cfe9c4f75ec7251391a4b0c1a5ef708053fd
#            scope:               "user "
        instagram:
            type:                instagram
            client_id:           c023c47bdfef408a88fc99f89e9c674b
            client_secret:       73ed66282b094604ba55e8bcbe50a7e6
            scope:               "public_content"
#        linkedin:
#            type:                linkedin
#            client_id:           77eupqrh1vyusp
#            client_secret:       cIXvfc18ybkMHfiw
#            infos_url:           "http://api.linkedin.com/v1/people/~:(id,formatted-name,email-address,picture-urls::(original))?format=json"
#            scope:               "r_basicprofile,r_emailaddress"
#            paths:
#                email:           emailAddress
#                profilepicture:  pictureUrl   


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:foundation_v5_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_comment:
    db_driver: orm
    class:
        model:
            comment: TunisiaMall\TunisiaMallTMBundle\Entity\Comment
            thread: TunisiaMall\TunisiaMallTMBundle\Entity\Thread

swiftmailer:
    transport: "%mailer_transport%"
    encryption: ssl
    auth_mode:  login
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    bundles: [ "FOSCommentBundle" ] 
    
nomaya_social:
    buttons:
        facebook:
            url:            null
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      false
            layout:         "button_count"
        twitter:
            url:            null
            locale:         "fr"
            message:        "Je veux partager ??a avec vous"
            text:           "Tweet"
            via:            "TunisiaMall"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:            
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    links: 
        facebook:           "http://www.facebook.com/Ben.Bader.M"
        googleplus:         "https://plus.google.com/105931415830389032796"
    theme:                  'default' # optional