tunisia_mall_user:
    resource: "@TunisiaMallUserBundle/Resources/config/routing.yml"
    prefix:   /



tunisia_mall_tm:
    resource: "@TunisiaMallTMBundle/Resources/config/routing.yml"
    prefix:   /
    
#-------------------------------------restes
app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@TunisiaMallUserBundle/Resources/config/routing/login.xml"
    prefix: /auth

hwi_oauth_connect:
    resource: "@TunisiaMallUserBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@TunisiaMallUserBundle/Resources/config/routing/redirect.xml"
    prefix:   /loginredirect

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

instagram_login:
    pattern: /login/check-instagram
    
twitter_login:
    pattern: /login/check-twitter

windows_live:
    pattern: /login/check-windows_live

github_login:
    pattern: /login/check-github
    
#linkedin_login:
#    pattern: /login/check-linkedin